### ISSUE TITLE
In Ubuntu is not guaranteed that /var/lib/locales/supported.d/local exists 

### ISSUE THREAD

**Issue by fonsecas72** [sous-chefs/locales#5]
I've run into this problem when trying to provision a docker container from scratch.
It seems that the /var/lib/locales/supported.d/local file is loaded by PAM but PAM is not invoked when using the docker container. 

I wonder if we can force the PAM to be invoked?

**Comment by ArturT** [comment]
I have the same problem but on OpenVZ and ubuntu-14.04-x86_64.

**Comment by BarthV** [comment]
I'll see next week if we can find a good awnser  for that issue.
Any help on this problem would be greatly appreciated :)

**Comment by Sliim** [comment]
Hi! 
I encountered the same issue on Ubuntu 12.04, but in virtual machine not a container. 
My workaround was to touch `/var/lib/locales/supported.d/local` manually.
@fonsecas72 are you sure that there is a link with PAM?

**Comment by Sliim** [comment]
Maybe we can check is file exists in this ruby_block: https://github.com/redguide/locales/blob/master/providers/default.rb#L80
Chef::Util::FileEdit raise exception if file doesn't exists: http://www.rubydoc.info/gems/chef/Chef/Util/FileEdit#initialize-instance_method [view source]
